// <auto-generated/>
#nullable enable

namespace Corvus.Json.SchemaGenerator{


[System.AttributeUsage(System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
public class GenerateModelsFromSchemaAttribute : System.Attribute
{
    public GenerateModelsFromSchemaAttribute(string schema, string namesace)
    {
        Schema = schema;
        Namespace = namesace;

        // TODO: Validate the schema & namespace
        // TODO: write a function that generates the models
    }

    public string Schema { get; }
    public string Namespace { get; }
}
}