using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

class Program
{
    static void Main(string[] args)
    {
        var generatedCode = GenerateCode();
        var outputPath = Path.Combine("/Users/pranayjoshi/Desktop/projects/CSharp/stf/", "GeneratedCode.cs"); /// change here
        File.WriteAllText(outputPath, generatedCode);
    }

    static string GenerateCode()
    {
        string generatedCode = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Corvus.Json.SchemaGenerator{

        
        [System.AttributeUsage(System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
        public class GenerateModelsFromSchemaAttribute : System.Attribute
        {
            public GenerateModelsFromSchemaAttribute(string schema, string namesace)
            {
                Schema = schema;
                Namespace = namesace;

                // TODO: Validate the schema & namespace
                // TODO: write a function that generates the models
            }

            public string Schema { get; }
            public string Namespace { get; }
        }
        }
        """;

        return generatedCode;
    }
}